# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Firebase-Storage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Analytics'
pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'FirebaseUI/Storage'
  # Pods for Firebase-Storage

  target 'Firebase-StorageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Firebase-StorageUITests' do
    # Pods for testing
  end

end
